#!/usr/bin/env python3
"""Generate lightweight KnowledgeVault dashboard pages.

This script reads the generated public repo registry and writes human/agent
navigation pages under 01-Dashboard. It is intentionally local-file-only: it does
not call GitHub directly, so it stays fast and safe inside daily maintenance.
"""
from __future__ import annotations

import json
import os
from datetime import date
from pathlib import Path
from typing import Any

OWNER = os.environ.get("VAULT_GITHUB_OWNER", "codysumpter-cloud")
TODAY = date.today().isoformat()


def vault_root() -> Path:
    here = Path(__file__).resolve()
    return here.parents[2]


def read_registry(root: Path) -> list[dict[str, Any]]:
    registry_path = root / "99-System" / "Repositories" / f"{OWNER}.public.repo-registry.json"
    if not registry_path.exists():
        return []
    return json.loads(registry_path.read_text(encoding="utf-8"))


def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content.strip() + "\n", encoding="utf-8")


def repo_table(registry: list[dict[str, Any]], limit: int = 20) -> str:
    rows = []
    for repo in sorted(registry, key=lambda item: item.get("name", "").lower())[:limit]:
        rows.append(
            "| "
            f"[[{OWNER}/{repo['name']}/Project|{repo['name']}]] | "
            f"`{repo.get('default_branch', 'main')}` | "
            f"[{repo['full_name']}]({repo['github_url']}) | "
            f"{repo.get('last_synced', TODAY)} |"
        )
    return "\n".join(rows) if rows else "| _No public repos indexed yet._ |  |  |  |"


def generate_today(root: Path, registry: list[dict[str, Any]]) -> None:
    write(root / "01-Dashboard" / "Today.md", f"""
---
type: dashboard
scope: today
date: {TODAY}
tags:
  - dashboard
  - today
  - agent-handoff
---

# Today — KnowledgeVault

Use this page as the daily starting point for humans and agents.

## Snapshot

- Date: {TODAY}
- Public repos indexed: {len(registry)}
- Source registry: `99-System/Repositories/{OWNER}.public.repo-registry.json`
- Safety check: run `python3 "99-System/Automation/vault_doctor.py"`

## Start here

1. [[Project Source of Truth]]
2. [[Repo Health]]
3. [[Open PRs]]
4. [[Agent Handoff]]
5. [[../BACKLOG|KnowledgeVault Backlog]]
6. [[../RUNBOOK|KnowledgeVault Runbook]]

## Operator note

KnowledgeVault is the book and memory layer. Verify runtime capability claims in the owning code repo before presenting them as implemented.
""")


def generate_repo_health(root: Path, registry: list[dict[str, Any]]) -> None:
    write(root / "01-Dashboard" / "Repo Health.md", f"""
---
type: dashboard
scope: repo-health
last_synced: {TODAY}
tags:
  - dashboard
  - github
  - repo-health
---

# Repo Health

This dashboard is generated from the public repo registry. It is a navigation layer, not a replacement for live GitHub status.

## Summary

- Public repos indexed: {len(registry)}
- Owner: `{OWNER}`
- Last generated: {TODAY}

## First 20 repos

| Repo | Default branch | GitHub | Last sync |
|---|---|---|---|
{repo_table(registry, limit=20)}

## Next upgrade

The next Vault Steward upgrade should enrich this page with live open issue counts, open pull request counts, recent activity, and CI status.
""")


def generate_open_prs(root: Path) -> None:
    write(root / "01-Dashboard" / "Open PRs.md", f"""
---
type: dashboard
scope: open-prs
last_synced: {TODAY}
tags:
  - dashboard
  - github
  - pull-requests
---

# Open PRs

This page is the intended home for generated open pull request summaries.

## Current status

Live PR enrichment is not yet generated by Vault Steward. Until that lands, agents should check GitHub directly before making claims about open pull requests, mergeability, or CI state.

## Manual checklist

For each active repo, capture:

- PR number and title
- branch
- mergeability
- checks status
- risk level
- recommended next action
- whether it blocks a public demo or release

## Next upgrade

Add a lightweight GitHub API enrichment pass that writes public-safe PR metadata here without exposing private repo names while the vault remains public.
""")


def generate_agent_handoff(root: Path, registry: list[dict[str, Any]]) -> None:
    write(root / "01-Dashboard" / "Agent Handoff.md", f"""
---
type: dashboard
scope: agent-handoff
last_synced: {TODAY}
tags:
  - dashboard
  - agent
  - handoff
---

# Agent Handoff

Read this before making changes in KnowledgeVault.

## Current operating direction

- OpenClaw is retired for current work.
- Hermes-agent is the current main working agent system.
- Buddy-agent is being prepared to become the primary runtime.
- KnowledgeVault is the book and memory layer.

## Required reading

1. `README.md`
2. `AGENTS.md`
3. `SYSTEMMAP.md`
4. `RUNBOOK.md`
5. `BACKLOG.md`
6. `SECURITY.md`
7. `01-Dashboard/Project Source of Truth.md`
8. `30 - Projects/GitHub/GitHub Projects Index.md`

## Current vault facts

- Public repos indexed: {len(registry)}
- Registry owner: `{OWNER}`
- Last generated: {TODAY}

## Safe change pattern

1. Make additive changes.
2. Preserve human-authored sections unless directly asked to rewrite them.
3. Do not present reference notes as implemented runtime features.
4. Run `python3 "99-System/Automation/vault_doctor.py"`.
5. Open a PR with clear receipts.
""")


def main() -> int:
    root = vault_root()
    registry = read_registry(root)
    generate_today(root, registry)
    generate_repo_health(root, registry)
    generate_open_prs(root)
    generate_agent_handoff(root, registry)
    print(f"Generated KnowledgeVault dashboards for {len(registry)} public repos.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
